### ISSUE TITLE
Ubuntu 22.04 package required

### ISSUE THREAD

**Issue by dimakuv** [microsoft/Azure-DCAP-Client#175]
Currently, there is no `az-dcap-client` package in `deb [arch=amd64] https://packages.microsoft.com/ubuntu/22.04/prod jammy main`. Could you add the package please?

**Comment by dzobbe** [comment]
Any update on this one?

**Comment by msft-gumunjal** [comment]
Hello, Azure DCAP won't be published for Ubuntu 22.04. The current recommendation is to use Intel QPL instead of Azure DCAP and update the config file to fetch collateral and certificates from Azure. For more information, please look at: https://learn.microsoft.com/en-us/azure/security/fundamentals/trusted-hardware-identity-management#how-do-i-use-intel-qpl-with-trusted-hardware-identity-management

**Comment by dimakuv** [comment]
@msft-gumunjal Does it mean that for Ubuntu 20.04, we also don't need to use the Azure DCAP client package? Does it mean that this package is completely deprecated, across all platforms and OS distros?

In other words, if I have my MS Azure VM with Ubuntu 20.04, do I also install Intel QPL instead of `azure-dcap` and modify the Intel QPL's config file?

**Comment by msft-gumunjal** [comment]
Going forward the recommended method is to use Intel QPL and not Azure DCAP. Azure DCAP package is not being deprecated as of now and we will continue to provide support for the platforms currently supported.

For 20.04, customers have the flexibility to use Azure DCAP or Intel QPL. On an Azure VM, customers need to install Intel QPL and modify the config file if they choose to use Intel QPL.
